# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-26 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20161126_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('0', 'Draft'), ('1', 'Submitted'), ('2', 'Canceled')], default='0', max_length=1),
            preserve_default=False,
        ),
    ]
