# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-26 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_session_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('a', 'Draft'), ('b', 'Submitted'), ('c', 'Canceled')], max_length=1),
        ),
    ]
