# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-26 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20161126_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('0', 'Draft'), ('1', 'Submitted'), ('2', 'Canceled')], max_length=1),
        ),
    ]
